### ISSUE TITLE
Add feedback link

### ISSUE THREAD

**Issue by rukayaj** [rukayaj/species#50]
Click link to send feedback to D's email address

**Comment by fhatani23** [comment]
how do you want to implement the feedback option? this I can do

**Comment by rukayaj** [comment]
Awesome! You can just add a link like <a href="mailto:D.VanDerColff@sanbi.org.za?Subject={{ taxon }} feedback from Species website">Email feedback</a> somewhere into assessment.html near the bottom maybe? I don't know if the {{ taxon }} will work, you can test and see.

**Comment by fhatani23** [comment]
This is sorted. one less thing to worry about.
