### ISSUE TITLE
Home page edits

### ISSUE THREAD

**Issue by DomitillaRaimondo** [rukayaj/species#72]
Add explore species as per mock up

Justify the main text and take the font size up one or two sizes

Line up logo with the S of the South African Species

Enlarge whole site name South African Species Information and Red Lists so it take up more of the banner

Send dimensions of jpegs under graph pixels by pixel (resolution) to Elizma please

**Comment by rukayaj** [comment]
I added explore species button in grey under the other. 

Not a good idea to justify text on the web, read about it here https://www.quora.com/Why-is-justified-text-alignment-so-rare-on-the-web

I have lined up logo with the S

I have enlarged the South African Species Information and Red Lists 

I have sent dimensions to Elizma.

These changes will be put online before the end of the day.
