### ISSUE TITLE
Add comment on assessment link

### ISSUE THREAD

**Issue by DomitillaRaimondo** [rukayaj/species#75]
please can you make an option where the user can send us feedback on an assessment - e.g. note an error in the information etc - offer to update and assessment. On our plant red list site we have this option see:
http://redlist.sanbi.org/species.php?species=796-19 

This should appear at the bottom of the Red List tab and should link to Dewidine's email address we do not want a contact us page as these are very prone to abuse -  loads of spam etc.

**Comment by rukayaj** [comment]
@fhatani23 I think you did a fix for this, did you commit it?
